## Rico's Numpy Cheat Sheet

This notebook contains resources and references for doing common things in numpy.

In [2]:
import numpy as np

## Converting continuous probabilities into binary classifications

Here's how to convert an array of probabilities from 0-1 into binary classifications of 0 or 1.  This is a vectorized implementation.

In [19]:
probabilities = np.array([0.1, 0.2, 0.4, 0.6, 0.8])
classifications = np.where(probabilities > 0.5, 1, 0)
print('probabilities', probabilities)
print('classifications', classifications)

probabilities [0.1 0.2 0.4 0.6 0.8]
classifications [0 0 0 1 1]


Note that depending on your application, you might want 1.0 and 0.0 instead of 1 and 0.

If you want binaries out, you can do this:

In [23]:
(probabilities > 0.5)

array([False, False, False,  True,  True])


## Putting formulas in notebooks

Here are some examples of putting formulas into notebooks.

Forward Propagation:
- You get X
- You compute $A = \sigma(w^T X + b) = (a^{(1)}, a^{(2)}, ..., a^{(m-1)}, a^{(m)})$
- You calculate the cost function: $J = -\frac{1}{m}\sum_{i=1}^{m}y^{(i)}\log(a^{(i)})+(1-y^{(i)})\log(1-a^{(i)})$

$$ \frac{\partial J}{\partial w} = \frac{1}{m}X(A-Y)^T\tag{7}$$
$$ \frac{\partial J}{\partial b} = \frac{1}{m} \sum_{i=1}^m (a^{(i)}-y^{(i)})\tag{8}$$

More on formatting formulas in notebooks: [Formatting notebooks](https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Working%20With%20Markdown%20Cells.html)

## Sums and axis

In [2]:
A = np.random.randn(4,3)
B = np.sum(A, axis = 1, keepdims = True)

In [3]:
A

array([[-0.92992221, -0.96606404, -0.5163828 ],
       [ 0.54193367,  0.51232707, -0.45697498],
       [ 1.60683307, -2.99889025,  0.13212601],
       [-0.03487388, -0.08024598, -0.23667623]])

In [4]:
B

array([[-2.41236905],
       [ 0.59728576],
       [-1.25993117],
       [-0.35179609]])

In [6]:
C = np.sum(A, axis = 0, keepdims = True)
C

array([[ 1.18397065, -3.53287319, -1.07790801]])

In [7]:
np.shape(B)

(4, 1)

In [8]:
np.shape(C)

(1, 3)

In [9]:
C2 = np.sum(A, axis = 0, keepdims = False)
C2

array([ 1.18397065, -3.53287319, -1.07790801])

## Multiply, dot, and *

In [10]:
A = np.array([[1,2,3],[4,5,6]])

In [11]:
B = np.array([[0,0.5,1],[1,2,3]])

In [12]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
B

array([[0. , 0.5, 1. ],
       [1. , 2. , 3. ]])

In [14]:
np.multiply(A,B)

array([[ 0.,  1.,  3.],
       [ 4., 10., 18.]])

In [15]:
A * B

array([[ 0.,  1.,  3.],
       [ 4., 10., 18.]])

In [16]:
np.dot(A,B)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [18]:
np.dot(A, B.T)

array([[ 4. , 14. ],
       [ 8.5, 32. ]])

## Array Slicing
Selecting a column from an array:

In [3]:
items = np.array([[1,2,3],[4,5,6],[7,8,9]])
items

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
items[:, 0] # Get first column

array([1, 4, 7])

In [6]:
items[:,0].T

array([1, 4, 7])